title: Kalinina Dariia # your name (or website title) here
logo: "/images/Attachment-1.jpeg?raw=true" # your photo (or logo) here
description: Junior FrontEnd Developer> # your text below (remove <br> elements if you don't need line breaks)
   
  <br/>
 Contact information 
  <br/>
  Phone: +38(067)483-18-09
  <br/>
  Email: dkalinina8@gmail.com
   <br/>
  <a href="https://github.com/KalinkinaD">Here is My GitHub Profile</a>
  <br/>
  <a href="https://www.linkedin.com/in/daria-kalinina-60aaaa168/">Here is My LinkedIn Profile</a> 
 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
