title: Kalinina Dariia 
logo: "/images/Attachment-1.jpeg?raw=true" 
description: Junior FrontEnd Developer 
   <br><br>
  <br/>
 Contact information 
  <br/>
  Email: dkalinina8@gmail.com
   <br/>
  <a href="https://github.com/KalinkinaD">Here is My GitHub Profile</a>
  <br/>
  <a href="https://www.linkedin.com/in/daria-kalinina-60aaaa168/">Here is My LinkedIn Profile</a> 
 
  
theme: jekyll-theme-minimal

